Repository ghojeong/baseball, pull requests merged in 2021-05, with the labels that each got.

#3 [BE] 스프링 초기화를 함
  be/server/.gitignore
  be/server/build.gradle
  be/server/gradle/wrapper/gradle-wrapper.jar
  be/server/gradle/wrapper/gradle-wrapper.properties
  be/server/gradlew
  be/server/gradlew.bat
  be/server/settings.gradle
  be/server/src/main/java/com/baseball/BaseballApplication.java
  be/server/src/main/resources/application.properties
  be/server/src/test/java/com/baseball/BaseballApplicationTests.java
Labels: BE

#5 [BE] OAuth 를 연습해보기 위한 웹 프론트 구현
  be/react-app/.gitignore
  be/react-app/README.md
  be/react-app/package.json
  be/react-app/public/index.html
  be/react-app/src/App.css
  be/react-app/src/App.tsx
  be/react-app/src/index.tsx
  be/react-app/src/pages/Home.tsx
  be/react-app/src/pages/Login.tsx
  be/react-app/src/pages/OAuth.tsx
  be/react-app/src/pages/Root.tsx
  be/react-app/src/pages/index.ts
  be/react-app/src/react-app-env.d.ts
  be/react-app/src/router/AppRouter.tsx
  be/react-app/src/router/const.ts
  be/react-app/src/service/axios.ts
  be/react-app/src/service/index.ts
  be/react-app/src/service/loginService.ts
  be/react-app/tsconfig.json
  be/react-app/yarn.lock
  be/server/src/main/java/com/baseball/config/WebConfig.java
  be/server/src/main/java/com/baseball/controller/AuthController.java
  be/server/src/main/java/com/baseball/dto/LoginRequest.java
  be/server/src/main/resources/application.properties
Labels: BE

#15 [BE] GET에 대한 요청 구현
  be/server/src/main/java/com/baseball/controller/BaseballController.java
  be/server/src/main/java/com/baseball/dto/BatterDto.java
  be/server/src/main/java/com/baseball/dto/GameInfoDto.java
  be/server/src/main/java/com/baseball/dto/InningsDto.java
  be/server/src/main/java/com/baseball/dto/LoginRequest.java
  be/server/src/main/java/com/baseball/dto/MatchDto.java
  be/server/src/main/java/com/baseball/dto/MatchInfoDto.java
  be/server/src/main/java/com/baseball/dto/PitcherDto.java
  be/server/src/main/java/com/baseball/dto/PlayersDto.java
  be/server/src/main/java/com/baseball/dto/ScoreDto.java
  be/server/src/main/java/com/baseball/service/BaseballService.java
Labels: BE

#14 [BE] 로컬 개발환경을 도커화
  be/docker/.gitignore
  be/docker/README.md
  be/docker/db/conf/custom.cnf
  be/docker/db/initdb/1-init.sql
  be/docker/docker-clear.sh
  be/docker/docker-compose.yml
  be/docker/docker-start.sh
  be/docker/nginx/conf/gateway.conf
  be/docker/nginx/nginx.conf
  be/server/src/main/java/com/baseball/controller/AuthController.java
Labels: BE

#17 [BE] Swagger 세팅
  be/README.md
  be/deploy.sh
  be/docker/docker-start.sh
  be/docker/nginx/conf/gateway.conf
  be/server/.gitignore
  be/server/build.gradle
  be/server/run.sh
  be/server/src/main/java/com/baseball/config/WebConfig.java
  be/server/src/main/java/com/baseball/controller/AuthController.java
  be/server/src/main/java/com/baseball/controller/BaseballController.java
  be/server/src/main/java/com/baseball/controller/SwaggerController.java
Labels: BE

#20 [BE] domain 설계
  be/server/src/main/java/com/baseball/domain/Batter.java
  be/server/src/main/java/com/baseball/domain/GameInfo.java
  be/server/src/main/java/com/baseball/domain/Innings.java
  be/server/src/main/java/com/baseball/domain/Match.java
  be/server/src/main/java/com/baseball/domain/MatchInfo.java
  be/server/src/main/java/com/baseball/domain/Pitcher.java
  be/server/src/main/java/com/baseball/domain/Players.java
  be/server/src/main/java/com/baseball/domain/Score.java
  be/server/src/main/java/com/baseball/dto/BatterDto.java
  be/server/src/main/java/com/baseball/dto/GameInfoDto.java
  be/server/src/main/java/com/baseball/dto/InningsDto.java
  be/server/src/main/java/com/baseball/dto/MatchDto.java
  be/server/src/main/java/com/baseball/dto/MatchInfoDto.java
  be/server/src/main/java/com/baseball/dto/PitcherDto.java
  be/server/src/main/java/com/baseball/dto/PlayersDto.java
  be/server/src/main/java/com/baseball/dto/ScoreDto.java
  be/server/src/main/java/com/baseball/repository/GameInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MatchInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MatchRepository.java
  be/server/src/main/java/com/baseball/repository/MockedGameInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchRepository.java
  be/server/src/main/java/com/baseball/service/BaseballService.java
Labels: BE

#24 [BE] 배포 스크립트 local 과 remote 용으로 분리
  be/README.md
  be/deploy-local.sh
  be/deploy-remote.sh
  be/server/build.gradle
  be/server/run.sh
Labels: BE

#32 [BE] 서비스 레이어에서의 인수 테스트 작성
  be/server/src/main/java/com/baseball/controller/BaseballController.java
  be/server/src/main/java/com/baseball/domain/InningInfo.java
  be/server/src/main/java/com/baseball/domain/InningResult.java
  be/server/src/main/java/com/baseball/domain/MatchInfo.java
  be/server/src/main/java/com/baseball/dto/InningInfoDto.java
  be/server/src/main/java/com/baseball/dto/MatchInfoDto.java
  be/server/src/main/java/com/baseball/repository/MockedGameInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchRepository.java
  be/server/src/main/java/com/baseball/service/BaseballService.java
  be/server/src/test/java/com/baseball/service/BaseballServiceTest.java
Labels: BE

#40 [BE] domain 객체가 3개 이하의 필드를 갖도록 리팩토링
  be/server/src/main/java/com/baseball/controller/BaseballController.java
  be/server/src/main/java/com/baseball/controller/ExceptionController.java
  be/server/src/main/java/com/baseball/domain/Batter.java
  be/server/src/main/java/com/baseball/domain/GameInfo.java
  be/server/src/main/java/com/baseball/domain/InningInfo.java
  be/server/src/main/java/com/baseball/domain/InningResult.java
  be/server/src/main/java/com/baseball/domain/Innings.java
  be/server/src/main/java/com/baseball/domain/Match.java
  be/server/src/main/java/com/baseball/domain/MatchInfo.java
  be/server/src/main/java/com/baseball/domain/Pitcher.java
  be/server/src/main/java/com/baseball/domain/Score.java
  be/server/src/main/java/com/baseball/domain/match/Match.java
  be/server/src/main/java/com/baseball/domain/match/MatchInfo.java
  be/server/src/main/java/com/baseball/domain/match/Matches.java
  be/server/src/main/java/com/baseball/domain/match/PitchResult.java
  be/server/src/main/java/com/baseball/domain/player/Batter.java
  be/server/src/main/java/com/baseball/domain/player/Pitcher.java
  be/server/src/main/java/com/baseball/domain/player/Player.java
  be/server/src/main/java/com/baseball/domain/player/Players.java
  be/server/src/main/java/com/baseball/domain/team/SelectedTeam.java
  be/server/src/main/java/com/baseball/domain/team/Team.java
  be/server/src/main/java/com/baseball/domain/team/Teams.java
  be/server/src/main/java/com/baseball/dto/BatterDto.java
  be/server/src/main/java/com/baseball/dto/GameInfoDto.java
  be/server/src/main/java/com/baseball/dto/InningInfoDto.java
  be/server/src/main/java/com/baseball/dto/InningsDto.java
  be/server/src/main/java/com/baseball/dto/MatchDto.java
  be/server/src/main/java/com/baseball/dto/MatchInfoDto.java
  be/server/src/main/java/com/baseball/dto/MatchRequestDto.java
  be/server/src/main/java/com/baseball/dto/PitcherDto.java
  be/server/src/main/java/com/baseball/dto/PlayersDto.java
  be/server/src/main/java/com/baseball/dto/ScoreDto.java
  be/server/src/main/java/com/baseball/exception/MatchNotFoundException.java
  be/server/src/main/java/com/baseball/exception/MatchOccupiedException.java
  be/server/src/main/java/com/baseball/repository/BaseballRepository.java
  be/server/src/main/java/com/baseball/repository/GameInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MatchInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MatchRepository.java
  be/server/src/main/java/com/baseball/repository/MockedBaseballRepository.java
  be/server/src/main/java/com/baseball/repository/MockedGameInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchInfoRepository.java
  be/server/src/main/java/com/baseball/repository/MockedMatchRepository.java
  be/server/src/main/java/com/baseball/service/BaseballService.java
  be/server/src/test/java/com/baseball/domain/match/MatchesTest.java
  be/server/src/test/java/com/baseball/domain/team/TeamsTest.java
  be/server/src/test/java/com/baseball/service/BaseballServiceTest.java
Labels: BE

#52 Refactor: FeedBack 반영 (#51)
  ios/baseball/.DS_Store
  ios/baseball/baseball/Service/Network/EndPoint.swift
  ios/baseball/baseball/Service/Network/NetworkService.swift
Labels: iOS

#50 [BE] TDD 로 도메인 기능 구현 (공수가 바뀌는 상황)
  be/deploy-remote.sh
  be/server/src/main/java/com/baseball/controller/BaseballController.java
  be/server/src/main/java/com/baseball/domain/match/Match.java
  be/server/src/main/java/com/baseball/domain/match/MatchInfo.java
  be/server/src/main/java/com/baseball/domain/match/PlayResult.java
  be/server/src/main/java/com/baseball/domain/player/Pitcher.java
  be/server/src/main/java/com/baseball/domain/team/Team.java
  be/server/src/main/java/com/baseball/domain/team/Teams.java
  be/server/src/main/java/com/baseball/dto/MatchInfoDto.java
  be/server/src/main/java/com/baseball/dto/ProgressRequestDto.java
  be/server/src/main/java/com/baseball/repository/MockedBaseballRepository.java
  be/server/src/test/java/com/baseball/BaseballApplicationTests.java
  be/server/src/test/java/com/baseball/domain/match/MatchInfoTest.java
  be/server/src/test/java/com/baseball/domain/match/MatchTest.java
  be/server/src/test/java/com/baseball/domain/match/MatchesTest.java
  be/server/src/test/java/com/baseball/domain/match/PlayResultTest.java
  be/server/src/test/java/com/baseball/domain/team/TeamFactory.java
  be/server/src/test/java/com/baseball/domain/team/TeamTest.java
  be/server/src/test/java/com/baseball/domain/team/TeamsTest.java
  be/server/src/test/java/com/baseball/service/BaseballServiceTest.java
Labels: BE

#54 [iOS] POST /api/match & /api/progress
  ios/baseball/Podfile
  ios/baseball/Podfile.lock
  ios/baseball/Pods/Manifest.lock
  ios/baseball/Pods/Pods.xcodeproj/project.pbxproj
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-acknowledgements.markdown
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-acknowledgements.plist
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-frameworks-Debug-input-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-frameworks-Debug-output-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-frameworks-Release-input-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-frameworks-Release-output-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests-frameworks.sh
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests.debug.xcconfig
  ios/baseball/Pods/Target Support Files/Pods-baseball-baseballUITests/Pods-baseball-baseballUITests.release.xcconfig
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-acknowledgements.markdown
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-acknowledgements.plist
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-frameworks-Debug-input-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-frameworks-Debug-output-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-frameworks-Release-input-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-frameworks-Release-output-files.xcfilelist
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball-frameworks.sh
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball.debug.xcconfig
  ios/baseball/Pods/Target Support Files/Pods-baseball/Pods-baseball.release.xcconfig
  ios/baseball/Pods/Target Support Files/Pods-baseballTests/Pods-baseballTests.debug.xcconfig
  ios/baseball/Pods/Target Support Files/Pods-baseballTests/Pods-baseballTests.release.xcconfig
  ios/baseball/baseball.xcodeproj/project.pbxproj
  ios/baseball/baseball.xcodeproj/xcuserdata/zombietux.xcuserdatad/xcschemes/xcschememanagement.plist
  ios/baseball/baseball/Assets.xcassets/야구공.imageset/Contents.json
  ios/baseball/baseball/Assets.xcassets/야구공.imageset/mirage-80.png
  ios/baseball/baseball/Domain/Entity/GameInfo.swift
  ios/baseball/baseball/Domain/Entity/MatchInfo.swift
  ios/baseball/baseball/Domain/Entity/PitchInfo.swift
  ios/baseball/baseball/Domain/Entity/Pitcher.swift
  ios/baseball/baseball/Domain/Entity/Score.swift
  ios/baseball/baseball/Domain/MatchViewModel.swift
  ios/baseball/baseball/Domain/UseCase/MatchUseCase.swift
  ios/baseball/baseball/Domain/UseCase/PlayUseCase.swift
  ios/baseball/baseball/Domain/UseCase/PlayViewModel.swift
  ios/baseball/baseball/Domain/UseCase/ScoreViewModel.swift
  ios/baseball/baseball/Domain/UseCase/UseCasePort.swift
  ios/baseball/baseball/Presentor/UI/Controller/GameListViewController.swift
  ios/baseball/baseball/Presentor/UI/Controller/PlayViewController.swift
  ios/baseball/baseball/Presentor/UI/Controller/ScoreViewController.swift
  ios/baseball/baseball/Presentor/UI/View/Base.lproj/Main.storyboard
  ios/baseball/baseball/Presentor/UI/View/Game/GradientView.swift
  ios/baseball/baseball/Presentor/UI/View/Game/TeamSelectAlertAction.swift
  ios/baseball/baseball/Presentor/UI/View/Play/GroundView.swift
  ios/baseball/baseball/Presentor/UI/View/Play/MatchBoardView.swift
  ios/baseball/baseball/Presentor/UI/View/Play/MatchBoardView.xib
  ios/baseball/baseball/Presentor/UI/View/Play/MatchUpView.swift
  ios/baseball/baseball/Presentor/UI/View/Play/PitchButton.swift
  ios/baseball/baseball/Presentor/UI/View/Play/PitchInfoCell.swift
  ios/baseball/baseball/Presentor/UI/View/Score/PlayersHistoryCell.swift
  ios/baseball/baseball/Presentor/UI/View/Score/RecodeHeaderView.swift
  ios/baseball/baseball/Presentor/UI/View/ScoreView.swift
  ios/baseball/baseball/Service/Network/EndPoint.swift
  ios/baseball/baseball/Service/Network/NetworkService.swift
Labels: Feature, iOS
